@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tamaized.beatdownstick.common;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;