modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Tamaized/BeatDownStick/issues"
license="MIT License"
[[mods]]
modId="beatdownstick"
version="${version}"
displayName="Beat Down Stick"
credits=""
authors="Tamaized"
description='''
Adds a Stick called the Beat Down Stick to annihilate your foes, including Creative Mode Players
'''

[[dependencies.beatdownstick]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.23,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beatdownstick]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"