@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tamaized.beatdownstick.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;