@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tamaized.beatdownstick.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;