@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tamaized.beatdownstick.common.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;