@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package tamaized.beatdownstick;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;